metonym/svelte-highlight

README.md, demo/routes/index.svelte, src/Highlight.svelte, src/HighlightAuto.svelte, src/HighlightSvelte.svelte, test/SvelteHighlight.test.svelte, types/Highlight.d.ts, types/HighlightAuto.d.ts, types/HighlightSvelte.d.ts
closes #170 
I found plenty of time to work on this today, it's only a small non-breaking change so it didn't take too long.
This could effect the behaviour of code for users who pass down a `data-language` attribute or who pass down a `langtag` class, though `$$restprops` should override this commit's additions and prevent issues.
---
First part:
Implementing the `data-language` attribute pretty much verbatim from #170. 
There was a bit of trouble with `data-language="undefined"` cropping up, so a fallback to `"plaintext"` has been added.
```html
<pre data-language="typescript" class="hljs s-abcd1234"> ... </pre>
``` 
*example of changes to output*
---
Second part:
Implementing and documenting the addition of language tags as I mentioned was my motive in #170.
However I've kept the CSS …
=> Language Identifiers

README.md, demo/app.css, demo/lib/ScopedStyle.svelte, demo/lib/ScopedStyleAuto.svelte, demo/lib/ScopedStyleSvelte.svelte, demo/routes/index.svelte, src/Highlight.svelte, src/HighlightAuto.svelte, src/HighlightSvelte.svelte
Closes #172 
I didn't have as much time to work on this as I thought this week, so this one took a little longer than I had hoped.
As well as the busy week, bug 4 had me scratching my head for some time.
In short, the issues caused by the fix to bug 1 mean that langtags would no longer receive the correct text color from `highlight.js`.
I tested various workarounds, however they all felt far too hacky, one of them included modifying `highlight.js`'s styles in a way that resulted in styles leaking out of scope. The solution I landed on was the documentation update.
Summary: the use of the `.hljs` class deviates from the intended use from `highlight.js` .
As to not require a major version, I suggest simply adding the class to the `<code />` as well as the `<pre />` .
In implementing the fix …
=> [BREAKING] Resolving styling issues + causes

SUPPORTED_LANGUAGES.md, SUPPORTED_STYLES.md, demo/lib/styles.json, package.json, scripts/utils/fs.js, yarn.lock
**Features**
- upgrade `highlight.js` to version 11.4.0 (net +1 style)
=> Upgrade `highlight.js` to v11.4.0

package.json, scripts/build-languages.js, scripts/build-styles.js, scripts/index.js, scripts/utils/create-markdown.js, scripts/utils/fs.js, scripts/utils/index.js, scripts/utils/to-pascal-case.js, scripts/utils/write-to.js, src/Highlight.svelte.d.ts, src/HighlightAuto.svelte.d.ts, src/HighlightSvelte.svelte.d.ts, tests/SvelteHighlight.test.svelte, tsconfig.json, yarn.lock
This PR adjusts the tsconfig.json to check JS files and adds JSDocs types based on TS errors.
It also uses [type-only imports](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export) in the Svelte component type definitions.
=> Refactor scripts, use type-only import in type definitions

README.md, demo/routes/index.svelte, src/HighlightAuto.svelte, tests/SvelteHighlight.test.svelte, tests/SvelteHighlight.test.ts
Fixes https://github.com/metonym/svelte-highlight/issues/197
```diff
- import hljs from "highlight.js/lib/core";
+ import hljs from "highlight.js";
```
=> fix(highlight-auto): use default highlight.js library for `HighlightAuto`

tests/SvelteHighlight.test.ts, tests/index.test.ts, tests/languages.test.ts, tests/styles.test.ts, tsconfig.json
The updates `tsconfig.json` to:
- omit specific extensions in `tsconfig.json#include` to resolve type error for ".svelte" files and remove "unused `@ts-expect-error` directive" warnings
- remove useless `tick` usage since `@testing-library/user-event` is awaited
- enable `resolveJsonModules` to resolve type error when importing `package.json`
- remove unused
=> test: resolve TS errors in test files

src/Highlight.svelte, src/HighlightAuto.svelte, src/HighlightSvelte.svelte, tests/SvelteHighlightPackage.test.svelte
**Fixes**
- remove `language` prop type from `HighlightAuto`
**Refactor**
- use `$$Events/$$Slots` interfaces for types
- reuse `Slots` interface exported from `Highlight` module context
=> fix(types): remove `language` prop type from `HighlightAuto`

examples/rollup-typescript/package.json, examples/rollup-typescript/yarn.lock, examples/rollup/package.json, examples/rollup/yarn.lock, examples/sveltekit/package.json, examples/sveltekit/yarn.lock, package.json, svelte.config.js, tests/SvelteHighlight.test.ts, vite.config.js, yarn.lock
This upgrades Vitest. A breaking change in 0.19 was that CSS is now added to the DOM.
This updates the tests to reset `document.head.innerHTML` before each test suite.
=> test: upgrade `vitest`, use `beforeEach` instead of `afterEach` callback

package.json, scripts/build-languages.js, scripts/build-styles.js, tests/SvelteHighlightPackage.test.svelte
When porting the example set-ups to TypeScript in #230, I noticed that type definitions were missing for `svelte-highlight/languages/*` and `svelte-highlight/styles/*`.
This PR generates the types as part of the library building process. Component definitions are auto-generated by `svelte2tsx`.
=> fix(types): generate types for `svelte-highlight/languages/*` and `svelte-highlight/styles/*`

README.md, examples/rollup/public/index.html, examples/rollup/rollup.config.js, examples/rollup/src/App.svelte, examples/rollup/src/DynamicImport.svelte, examples/sveltekit/src/routes/DynamicImport.svelte, examples/sveltekit/src/routes/index.svelte, examples/vite/src/App.svelte, examples/vite/src/DynamicImport.svelte, examples/webpack/src/App.svelte, examples/webpack/src/DynamicImport.svelte
Closes #219
This PR documents code-splitting using the `dynamic import` syntax.
- add a "Code-splitting" recipe to the `README`
- add a `DynamicImport` component to each of the example set-ups
=> docs: add dynamic import example for code-splitting

SUPPORTED_LANGUAGES.md, SUPPORTED_STYLES.md, package.json, yarn.lock
- upgrade `highlight.js` to version [11.7.0](https://github.com/highlightjs/highlight.js/releases/tag/11.7.0)
=> feat(deps): upgrade highlight.js 11.6.0 -> 11.7.0

README.md, demo/lib/LineNumbers/Basic.svelte, demo/lib/LineNumbers/HideBorder.svelte, demo/lib/LineNumbers/StyleProps.svelte, demo/lib/LineNumbers/WrapLines.svelte, demo/routes/+page.svelte, src/LineNumbers.svelte, src/index.ts, tests/SvelteHighlight.test.svelte, tests/SvelteHighlight.test.ts, tests/SvelteHighlightPackage.test.svelte, tests/index.test.ts
Closes #247, related #240
This adds support for line numbers.
Create a `LineNumbers` component to be composed with either `Highlight`, `HighlightAuto`, or `HighlightSvelte`. `LineNumbers` is its own component for performance reasons (i.e., do not punish consumers who do not use it with extra code).
`highlighted` code must be passed as prop to `LineNumbers`.
```svelte
<script>
import Hightlight, { LineNumbers } from "svelte-highlight";
import typescript from "svelte-highlight/languages/typescript";
import atomOneDark from "svelte-highlight/styles/atom-one-dark";
const code = "const add = (a: number, b: number) => a + b";
</script>
<svelte:head>
{@html atomOneDark}
</svelte:head>
<Highlight language={typescript} {code} let:highlighted>
<LineNumbers {highlighted} />
</Highlight>
```
Set …
=> feat: add `LineNumbers`

README.md, demo/lib/LineNumbers/Basic.svelte, demo/lib/ScopedStyle.svelte, demo/lib/ScopedStyleAuto.svelte, demo/lib/ScopedStyleSvelte.svelte, demo/routes/+layout.svelte, demo/routes/+page.svelte, demo/routes/languages/+page.svelte, demo/routes/styles/+page.svelte, src/Highlight.svelte, src/HighlightAuto.svelte, src/HighlightSvelte.svelte, src/index.ts, tests/SvelteHighlight.test.ts, tsconfig.json, vite.config.js
**Refactoring**
- remove `prettier-ignore` comment since `prettier-plugin-svelte` correctly formats `pre` tags
**Docs**
- use path aliases
- use the active voice where possible
- use warn notification for auto-highlighting note
=> docs: improve docs, use path aliases

src/Highlight.svelte, src/HighlightAuto.svelte, src/HighlightSvelte.svelte, tests/SvelteHighlight.test.svelte
Closes #215
This is technically a breaking change so the major version should be incremented.
This changes the semantics of how `code` and `language` props are typed. Both should be required. To do this in Svelte, the props should not be assigned a default value.
=> fix!: mark `code`, `language` props as required

README.md, src/Highlight.svelte, src/HighlightAuto.svelte, tests/SvelteHighlight.test.svelte, tests/SvelteHighlight.test.ts
**Features**
- include the inferred `language` name in `on:highlight` event detail
**Fixes**
- `e.detail.highlighted` is a string
```svelte
<HighlightAuto
code={`body {\n  padding: 0;\n  color: red;\n}`}
on:highlight={(e) => {
console.log(e.detail.language); // "css"
}}
/>
```
=> feat(highlight-auto): include `language` in "on:highlight" event detail

src/LineNumbers.svelte, tests/SvelteHighlight.test.ts
Fixes #258
Top/bottom padding on `LineNumbers` is incorrectly set if `code` changes. Instead, we can use CSS to apply the padding.
=> fix(line-numbers): correctly set top/bottom padding

src/Highlight.svelte, src/HighlightAuto.svelte, src/HighlightSvelte.svelte, src/LangTag.svelte, src/LineNumbers.svelte, src/shared.d.ts, tests/SvelteHighlight.test.ts, tests/SvelteHighlightPackage.test.svelte
Closes #261
Currently, lang tag logic is duplicated in three different files. This extracts them into an internal component to reduce duplication.
It also:
- sets "initial" as the default value for CSS variables in the `langtag::after` rule (hence the updated snapshot test)
- adds a type check for `HighlightAuto`
- reuses `Props/Slots/Events` as much as possible
=> refactor: extract lang tag into an internal component

src/Highlight.svelte
The `language` check can be removed since #218 marked the `language` prop as required.
=> refactor(highlight): remove unnecessary truthy check

README.md, demo/lib/LineNumbers/HighlightedLines.svelte, demo/lib/LineNumbers/HighlightedLinesCustomColor.svelte, demo/routes/+page.svelte, src/LineNumbers.svelte, tests/SvelteHighlight.test.ts
Closes #256
Supports highlighting specific lines through the `highlightedLines` prop. Customize the background color using `--highlighted-background` style prop.
```svelte
<Highlight language={typescript} {code} let:highlighted>
<LineNumbers {highlighted} highlightedLines={[1, 2]} --highlighted-background="#000" />
</Highlight>
```
---
=> feat(line-numbers): support highlighted lines

examples/rollup/package.json, examples/rollup/yarn.lock, examples/routify/package.json, examples/routify/yarn.lock, examples/sveltekit/package.json, examples/sveltekit/yarn.lock, examples/vite/package.json, examples/vite/yarn.lock, examples/webpack/package.json, examples/webpack/webpack.config.js, examples/webpack/yarn.lock
Upgrades the example set-ups to use Svelte 4, TypeScript 5+ etc..
=> chore(examples): upgrade to svelte 4

scripts/build-languages.js, scripts/build-styles.js
There's a subtle but important difference between `export const` and `export declare const` when used in a type definition file.
- `export const` both declares and exports a constant.
- `export declare const` signifies types for a variable that is created elsewhere.
`declare` should be used in this case, since it's a type definition file; the variable is exported elsewhere.
=> fix(types): style/lang types should use declare const

scripts/npm-package.js
Fixes #315
`package.json#exports` needs additional entries to the library code.
This fixes resolution of the following import methods:
```ts
// Base import for styles/languages
import { _default } from "svelte-highlight/styles";
import { _1c } from "svelte-highlight/languages";
// Explicit index
import { _default } from "svelte-highlight/styles/index";
import { typescript } from "svelte-highlight/languages/index";
// Explicit extension
import lang from "svelte-highlight/languages/1c.js"
import style from "svelte-highlight/styles/3024.js";
```
=> fix(exports): include additional `exports` in package.json

README.md, src/Highlight.svelte.d.ts, src/HighlightAuto.svelte.d.ts, src/HighlightSvelte.svelte.d.ts, src/LangTag.svelte, src/LangTag.svelte.d.ts, tests/e2e/HighlightAuto.test.svelte, www/app.css, www/components/globals/Index.svelte
Closes #324
Customize the `langtag` padding using the `--langtag-padding` style prop. The default value is `"1em"`.
```svelte
<HighlightAuto
{code}
langtag
--langtag-background="linear-gradient(135deg, #2996cf, 80%, white)"
--langtag-color="#fff"
--langtag-border-radius="6px"
--langtag-padding="0.5rem"
/>
```
=> feat: add `--langtag-padding` style prop

src/Highlight.svelte.d.ts, src/HighlightAuto.svelte.d.ts, src/HighlightSvelte.svelte.d.ts, src/LangTag.svelte.d.ts, tests/SvelteHighlightPackage.test.svelte, www/components/globals/Index.svelte
`langtag`-related props can be reused, making it easier to update across all places.
=> Refactor langtag props

README.md, src/Highlight.svelte.d.ts, src/LangTag.svelte, tests/SvelteHighlightPackage.test.svelte, www/components/globals/Index.svelte
Closes #324
Related #325. Exposes `--langtag-top` and `--langtag-right` as style props.
```svelte
<HighlightAuto
{code}
langtag
--langtag-top="0.5rem"
--langtag-right="0.5rem"
--langtag-background="linear-gradient(135deg, #2996cf, 80%, white)"
--langtag-color="#fff"
--langtag-border-radius="6px"
--langtag-padding="0.5rem"
/>
```
=> feat: add `--langtag-top`, `--langtag-right` style props

src/LineNumbers.svelte
=> fix(line-numbers): avoid self-closing tag to address Svelte 5 warning

scripts/build-styles.ts
Supporting #233 
Use `postcss` to scope styles. The approach is to use the module name of the style to prefix parsed selectors.
This is the first step to supporting scoped styles – to dogfood the experience in the live demo site.
=> chore(scripts): use `postcss` to trial scoped styles

README.md
#352 
Adds an example that uses a custom `highlight.js` plugin (which is a "custom language").
=> docs: add custom plugin example

scripts/build-styles.ts, scripts/utils/minify-css.ts, tests/minify-css.test.ts
The processed JS styles (e.g., `arta.js`) preserve license-related comments while optimizing output. However, the same effect is not applied to processed CSS files (`arta.css`).
=> fix: preserve license comments in processed CSS

scripts/build-styles.ts, scripts/utils/minify-css.ts, scripts/utils/postcss-inline-css-vars.ts, scripts/utils/postcss-scoped-styles.ts, tests/postcss-inline-css-vars.test.ts, tests/postcss-scoped-styles.test.ts
Supporting #355, a plugin to inline CSS vars is needed to accommodate new themes from highlight.js@11.11.
=> build: extract PostCSS plugins

scripts/build-styles.ts, scripts/utils/preprocess-styles.ts, tests/preprocess-styles.test.ts
For clarity, rename the function and add some comments.
=> chore: rename `minify-css` to `preprocess-styles`

examples/webpack/webpack.config.mjs, src/Highlight.svelte, src/HighlightAuto.svelte, src/HighlightSvelte.svelte, src/LangTag.svelte, src/LineNumbers.svelte, tsconfig.json, www/components/CodeSnippet.svelte, www/components/Footer.svelte, www/components/LineNumbers/Basic.svelte, www/components/LineNumbers/HideBorder.svelte, www/components/LineNumbers/HighlightedLines.svelte, www/components/LineNumbers/HighlightedLinesCustomColor.svelte, www/components/LineNumbers/StartingLineNumber.svelte, www/components/LineNumbers/StyleProps.svelte, www/components/LineNumbers/WrapLines.svelte, www/components/ListSearch.svelte, www/components/ScopedLanguage.svelte, www/components/ScopedStyle.svelte, www/components/ScopedStyleAuto.svelte, www/components/ScopedStyleSvelte.svelte, www/components/globals/Header.svelte, www/components/globals/Index.svelte, www/components/globals/Languages.svelte, www/components/globals/Styles.svelte
Instead of including `@ts-check` comments directly in source code, enable `checkJs: true` in `tsconfig.json`.
=> chore: remove `@ts-check` comments

README.md, src/index.d.ts, tests/languages.test.ts
Fixes #373 
`LanguageType` is a utility for instrumenting custom `language` implementations for `highlight.js`. It's meant to be used by consumers, so this should be exported.
```ts
interface LanguageType<TName extends string> {
name: TName;
register: LanguageFn;
}
```
Example usage:
```ts
import type { LanguageType } from "svelte-highlight";
const language: LanguageType<"custom-language"> = {
name: "custom-language",
register: () => {
return {
contains: [],
tokenize: () => {
return {
tokens: [],
};
},
};
},
};
```
=> fix(types): export `LanguageType` utility type
